srcDir = "D:\\GObackup\\hello\\srcf"
dstDir = "D:\\GObackup\\hello\\dstf"

maxWorkers = 10 #max files to process concurrently

memUsage = 102400 # in bytes
maxFileSize = 1048576  # in bytes

backupFreq = 1 # in minutes


[restrictedDirs]
"test" = true

[restrictedFiles]
"test.exe" = true
"test.ps1" = true

[restrictedExtensions]
".sigma" = true

