srcDir = "D:\\GObackup\\hello\\srcf"
dstDir = "D:\\GObackup\\hello\\dstf"

maxWorkers = 10 #max files to process concurrently

memUsage = 104857600 # in bytes
maxFileSize = 2147483648  # in bytes

backupFreq = 30 # in minutes


[restrictedDirs]
"test" = true

[restrictedFiles]
"test.exe" = true
"test.ps1" = true

[restrictedExtensions]
".sigma" = true
".exe" = true

