srcDir = "D:\\GObackup\\hello\\srcf"
dstDir = "D:\\GObackup\\hello\\dstf"

maxWorkers = 10 
memUsage = 102400
maxFileSize = 1048576  # 1 MB

backupFreq = 1 # minutes


[restrictedDirs]
"test" = true

[restrictedFiles]
"test.exe" = true
"test.ps1" = true

[restrictedExtensions]
".sigma" = true

